import type { Metadata } from "next";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Bimbel Bumi Cerdas",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
      <div className="">
        <Navbar />
        <div>{children}</div> {/* Ensure this is correctly rendering */}
      </div>
    );
  }
  
