import type { Metadata } from "next";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Bimbel Bumi Cerdas",
  description: "Generated by create next app",
};

export default function ProgramLayout({
  children, 
}: {
  children: React.ReactNode
}) {
    return (
      <>
        <Navbar />
        <div>{children}</div>
      </>
    );
  }
  
